version: "3"

services:

  db:
    container_name: {{ project_name }}_db
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD={{ project_name }}_pass
      - POSTGRES_USER={{ project_name }}_user
      - POSTGRES_DB={{ project_name }}_db

  server:
    container_name: {{ project_name }}_server
    build: .
    command: gunicorn -b 0.0.0.0:8000 core.wsgi --log-file -
    environment:
      - DATABASE_URL=postgres://{{ project_name }}_user:{{ project_name }}_pass@db/{{ project_name }}_db
      - ALLOWED_HOSTS=*
      - PRODUCTION=1
    ports:
      - "8000:8000"
    links:
      - db
