version: "3"

services:
  server:
    command: python manage.py runserver 0.0.0.0:8000 --migrate
    environment:
      - PRODUCTION=false
      - ALLOWED_HOSTS=*
    volumes:
      - .:/app

  database:
    volumes:
      - ./.devdb/pgsql:/var/lib/postgresql/data
