FROM python:3.6.5

WORKDIR /app/

# Install dependencies first to keep it cached on file changes
COPY setup.py .
RUN mkdir -p core/helpers && touch core/__init__.py
COPY core/helpers/* ./core/helpers/

# Install dependencies
RUN python setup.py develop
# Remove folder generated by setup.py
RUN rm -r *.egg*

# Cleanup, since "gettext" was installed through apt-get
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . .

RUN ./manage.py collectstatic --no-input
RUN ./manage.py compilemessages
