#!/usr/bin/env bash

function print_red () {
  printf "\033[91m${1}\033[0m\n"
}

function print_yellow () {
  printf "\033[93m${1}\033[0m\n"
}

cd $(dirname ${0})

PROJECT_PATH=$(dirname $(dirname $(pwd)))

cd ${PROJECT_PATH}

which flake8 > /dev/null

if [[ ! ${?} -eq 0 ]]; then
  # If Flake8 isn't installed, the setup didn't run
  ${PROJECT_PATH}/bin/setup_dev_env.sh
fi

FLAKE8_OUTPUT=`git diff --cached | flake8 --diff 2>&1`

STATUS_CODE=$?

if [[ ! ${STATUS_CODE} -eq 0 ]]; then
  print_red "Flake8 caught some errors. See below:"
  print_yellow "${FLAKE8_OUTPUT}"
fi

exit ${STATUS_CODE}
