#!/usr/bin/env bash

PROJECT_PATH=$(dirname $(dirname $(dirname ${0})))

`${PROJECT_PATH}/compose.sh run ./scripts/pylint.sh`
PY_LINT=${?}
`${PROJECT_PATH}/compose.sh run ./scripts/flake8.sh`
FLAKE8=${?}
`${PROJECT_PATH}/compose.sh run ./scripts/bandit.sh`
BANDIT=${?}

if [[ ${PY_LINT} != 0 ]] || [[ ${FLAKE8} != 0 ]] || [[ ${BANDIT} != 0 ]]; then
  exit 1
fi
